keep/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include("landing.urls",namespace="landing")),

]

landing/urls.py
#Urls de app landing
from django.conf.urls import url
from .views import index,agregar,detalle

urlpatterns = [
    url(r'^$',index, name = "index"),
    url(r'^agregar/$',agregar, name="agregar"),
    url(r'^detalle/(?P<pk>[0-9]+)/$',detalle, name="detalle"),

]

landing/models.py
from django.db import models

# Create your models here.

class Reminder(models.Model):
	PRIORIDADES = (
		("AT","Alta"),
		("NR", "Normal"),
		("BJ", "Baja"),

		)

	id = models.AutoField(primary_key=True)
	titulo = models.CharField(max_length=60)
	descripcion = models.TextField()
	prioridad = models.CharField(max_length=30,
	choices = PRIORIDADES)
	fecha_creacion = models.DateTimeField(auto_now=True)

	def __str__(self):
		return"Reminder N° %s sobre: %s" % (str(self.id),self.titulo)

landing/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from .models import Reminder
# Create your views here.

def index(request):
    #Queryset
    # SELEC * FROM Reminder
    remainders = Reminder.objects.all()
    print (remainders)
    return render(request,"landing/index.html",{"recordatorios":remainders})
        
        
def agregar(request):
    if request.method == 'POST':
        remainder = Reminder()
        remainder.titulo = request.POST['titulo']
        remainder.descripcion = request.POST['descripcion']
        remainder.prioridad = request.POST['prioridad']
        remainder.save()
        return redirect('landing:index')
    else:
        return render(request,"landing/agregar.html")

def detalle(request,pk):

    try:
        remainder = Reminder.objects.get(id=pk)

    except:
        raise Http404

    return render(request,'landing/detalle.html',{"recordatorio":remainder})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title%}{%endblock%}</title>
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    {% block css %}
    
    {% endblock %}
</head>
<body>
           
    <nav>
    <div class="nav-wrapper">
      <a href="{% url 'landing:index' %}" class="brand-logo">Clone Keep</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'landing:agregar' %}">Agregar Recordatorio</a></li>      </ul>
    </div>
  </nav>
   {% block content%}

    {% endblock %}      
  
   
   
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="{% static 'js/materialize.js'%}"></script>
</body>
</html>

templates/landing/agregar.html
{% extends "base.html" %} 
   {% block title %} Agregar {% endblock %}
    
    {% block content %}
       <div class="row">
    <form class="col s12" action="{% url 'landing:agregar' %}" method="POST">
    	{% csrf_token %} 
      <div class="row">
        <div class="input-field col s6">
          <input placeholder="titulo" id="titulo" type="text" name="titulo" class="validate">
          <label for="titulo">Titulo</label>
        </div>
        <div class="input-field col s12">
          <textarea id="descripcion" name="descripcion" class="materialize-textarea"></textarea>
          <label for="descripcion">Descripción</label>
        </div>
      </div>
      <div class="row">
         <label>Prioridad</label>
            <select class="browser-default" name = "prioridad">
                <option value="" disable selected>Choose your option</option>
                <option value="AT">Alta</option>
                <option value="NR">Normal</option>
                <option value="BJ">Baja</option>
            </select>
      </div>
      <div class="row">
         <button class="waves-effect waves-light btn" type="submit" >Guardar</button>
      </div>
     
    </form>
  </div>
    {% endblock %}

templates/landing/detalle.html
{% extends "base.html" %}
{% block title %}Detalle{% endblock %}
{% block content %}
	<div class="row">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">{{recordatorio.titulo}}</span>
              <p>{{recordatorio.descripcion}}</p>
            </div>
            <div class="card-action">
             <span>{{recordatorio.prioridad}}</span>
             <span>{{recordatorio.fecha.creacion}}</span>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/landing/index.html
{% extends "base.html" %}
    {% block title %} Index {% endblock %}

    {% block content %}

        <div class="row"> 
        {% for recordatorio in recordatorios %}
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">{{recordatorio.titulo}}</span>
              <p>{{recordatorio.descripcion}}</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
              <a href="{% url 'landing:detalle' recordatorio.id %}">Detalle</a>
            </div>
          </div>
        </div>
      </div>
           
        {% endfor %}    
    {% endblock %}